is_dark_mode = true
is_system_dark_mode = true
is_system_both_dark_mode = true
auto_mode_change = false
auto_system_mode_change = false
custom_night_start = "08:00:00"
custom_night_end = "05:00:00"
custom_night_start_hh = 8
custom_night_start_mm = 0
custom_night_end_hh = 5
custom_night_end_mm = 0
custom_system_night_start = "00:00:00"
custom_system_night_end = "00:00:00"
custom_system_night_start_hh = 0
custom_system_night_start_mm = 0
custom_system_night_end_hh = 0
custom_system_night_end_mm = 0
is_autostart = false
