is_dark_mode = false
is_system_dark_mode = false
is_system_both_dark_mode = false
auto_mode_change = false
auto_system_mode_change = false
custom_night_start = "18:00:00"
custom_night_end = "08:00:00"
custom_night_start_hh = 18
custom_night_start_mm = 0
custom_night_end_hh = 8
custom_night_end_mm = 0
custom_system_night_start = "18:00:00"
custom_system_night_end = "08:00:00"
custom_system_night_start_hh = 18
custom_system_night_start_mm = 0
custom_system_night_end_hh = 8
custom_system_night_end_mm = 0
is_autostart = false
