name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build and bundle
        run: |
          cargo build --release
          cargo bundle --release

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target\release\autodark_egui_rr_test.exe  # 替换成你的应用程序路径
          asset_name: autodark_egui_rr_test.exe   # 替换成你的应用程序名称
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN:  ${{ secrets.TEST }}


