name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Build and bundle
          run: |
              cargo build --release
        - name: Archive extension
          run: mv target/release/*.exe dist/ 

        - name: Upload release artifact
          uses: actions/upload-artifact@v2
          with:
            name: autodark_rust
            path: dist
  release:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download release artifact
      uses: actions/download-artifact@v2
      with:
        name: autodark_rust
        path: dist

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        name: Release - ${{ github.ref_name }} # 使用标签名称作为 Release 标题
        
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
        tag: ${{ github.ref_name }}
    - name: Publish Release
      run: echo "Release published at ${{ steps.create_release.outputs.url }}"


          

  

          
